apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jrfw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jrfw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jrfw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jrfw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jrfw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zzcr-tenant/rhtap-demo-app/hacbs-test-project-jrfw@sha256:de491b2e11de922bf14bbd24e3bf3b2570c98c5b8f8f36595cd7067ddf5312a5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
